version: "3"

vars:
  CLUSTER_ID: "{{.CLUSTER_ID}}" # 指定集群ID，优先级比指定context高！
  CLUSTER_TYPE: "{{.CLUSTER_TYPE}}" # 集群类型，host => 托管
  CONTEXT: >-
    {{- if .CLUSTER_ID -}} cls
    {{- else}}{{.CONTEXT}}
    {{- end}}
  NAMESPACE: >-
    {{- if .CLUSTER_ID}}
      {{- if eq .CLUSTER_TYPE "host"}} {{- .CLUSTER_ID}}
      {{- else}}kube-system
      {{- end}}
    {{- else}}{{.NAMESPACE}}
    {{- end}}
  KUBECTL: >-
    kubectl
    {{if .CONTEXT}}--context={{.CONTEXT}}{{end}}
    {{if .NAMESPACE}}--namespace={{.NAMESPACE}}{{end}}
  WORKLOAD: "{{.WORKLOAD}}"
  # FIXME: https://github.com/go-task/task/issues/1611
  _WORKLOAD: >-
    {{- if .CLUSTER_ID}}
      {{- if eq .CLUSTER_TYPE "host"}}
        {{- .WORKLOAD | replace "/" (printf "/%s-" .CLUSTER_ID)}}
      {{- else -}} {{.WORKLOAD}}
      {{- end}}
    {{- else -}} {{.WORKLOAD}}
    {{- end}}
  CONTAINER: "{{.CONTAINER}}"
  _LOGIN: >-
    {{- if .CLUSTER_ID -}} kubectl ianvs login {{.CLUSTER_ID}}
      {{- if eq .CLUSTER_TYPE "host"}} --meta
      {{- end}}
    {{- end}}

set:
  - nounset
  - errexit
  - pipefail

tasks:
  set-image:
    desc: "更新镜像"
    vars:
      CONTAINER: "{{.CONTAINER}}"
      _CURRENT_VERSION:
        sh: >-
          {{if ._LOGIN}}{{._LOGIN}} 1>/dev/null && {{end}}
          {{.KUBECTL}} get {{._WORKLOAD}} -ojson | jq -r '.spec.template.spec.containers[] | select(.name == "{{.CONTAINER}}").image'
      VERSION:
        sh: >-
          echo {{._CURRENT_VERSION}} | sed 's/:.*/:{{.VERSION}}-linux-amd64/'
    cmds:
      - echo "{{._CURRENT_VERSION}} => {{.VERSION}}"
      - "{{.KUBECTL}} set image {{._WORKLOAD}} {{.CONTAINER}}={{.VERSION}}"
      - "{{.KUBECTL}} rollout restart {{._WORKLOAD}}"

  undo:
    desc: "回滚变更"
    cmds:
      - "{{.KUBECTL}} rollout undo {{._WORKLOAD}}"
